secretGenerator:
- name: mysql-db
  literals:
  - database=YOUR_DATABASE
- name: mysql-usr
  literals:
  - user=YOUR_USER
- name: mysql-pass
  literals:
  - password=YOUR_PASSWORD
resources:
- mysql-deployment.yaml
- wordpress-deployment.yaml
- wordpress-ingressroute.yaml
- wordpress-headers.yaml
- wordpress-ipwhitelist.yaml
