apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config-static
  namespace: default
  labels:
    app: traefik
data:
  traefik.yml: |
    entryPoints:
      web:
        address: :80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              
      websecure:
        address: :443
        http:
          tls:
            options: default-mytlsoption 
            certResolver: myresolver
            
    accessLog: {}
      
    providers:
      kubernetesCRD: {} 

    api:
      insecure: true
      
    certificatesResolvers:
      myresolver:
        acme:
          email: "foo.bar@mydomain.com"
          storage: "/letsencrypt/acme.json"
          tlsChallenge: {} 
