apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          ports:
            - name: websecure
              containerPort: 443
          volumeMounts:
            - name: traefik-persistent-storage
              mountPath: /letsencrypt
      volumes:
        - name: traefik-persistent-storage
          persistentVolumeClaim:
            claimName: traefik-pv-claim
